{
 "title": "Energy Monitoring",
 "description": "Energy monitoring dashboard based on ESP32 and PZEM004T",
 "tags": [
  "esp32",
  "pzem004t",
  "pzem",
  "energy"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Consuming Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "energy_power_total{}", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Current Power Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 10, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    { "expr": "energy_power_current{}", "legendFormat": "Current:" }
   ]
  },
  {
   "title": "Online From",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsSystem" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "energy_device_first_start_timestamp{} * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Last Update",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 19, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsSystem" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "energy_last_scrape_timestamp{} * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Consuming Total for Yesterday",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "energy_power_yesterday_total{}", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Consuming Total for Today",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "energy_power_today_total{}", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Network Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Voltage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 11, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "volt" } },
     "targets": [
      { "expr": "energy_voltage_current{}", "legendFormat": "Current:" }
     ]
    },
    {
     "title": "Amperage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 10, "x": 11, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "amp" } },
     "targets": [
      { "expr": "energy_amperes_current{}", "legendFormat": "Current:" }
     ]
    },
    {
     "title": "Frequency",
     "type": "stat",
     "gridPos": { "h": 8, "w": 3, "x": 21, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "Hz" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "energy_frequency_current{}", "legendFormat": "__auto" }
     ]
    }
   ]
  },
  {
   "title": "Power Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Apparent Power, VA",
     "type": "timeseries",
     "description": "Apparent Power specifies the electrical power supplied to a load. To distinguish it from Real power, the value is specified in volt-amperes (VA)",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "voltamp" } },
     "targets": [
      {
       "expr": "energy_power_apparent_current{}",
       "legendFormat": "Current:"
      }
     ]
    },
    {
     "title": "Reactive Power,  VAr",
     "type": "timeseries",
     "description": "In electrical grid systems, reactive power is the power that flows back from a destination toward the grid in an alternating current scenario",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "voltampreact" } },
     "targets": [
      {
       "expr": "energy_power_reactive_current{}",
       "legendFormat": "Current:"
      }
     ]
    },
    {
     "title": "Power Factor",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 3 },
     "targets": [
      { "expr": "energy_power_factor_current{}", "legendFormat": "Current:" }
     ]
    }
   ]
  }
 ]
}